### ISSUE TITLE
add extraInserts to add-in discovery package `addinslist`

### ISSUE THREAD

**Issue by salim-b** [konradzdeb/extraInserts#1]
Hi Konrad

Thanks for writing this package! I was thinking about creating a similar add-in myself just to be able to add a keyboard shortcut for magrittr's compound assignment pipe-operator. Now fortunately I stumbled upon your package which is exactly what I was looking for! 😃

I also noticed that there's a package called [addinslist](https://github.com/daattali/addinslist) with the goal to facilitate finding other RStudio add-ins. Yours isn't listed yet and I thought I should ask you first before making a pull request to add `extraInserts` to that list. Do you agree to get listed there? Do you want to add it yourself or should I do it?

Thanks a lot,
Salim

**Comment by konradzdeb** [comment]
Hi Salim,

Thanks for your message and showing interest. I will be happy for `extraInserts` to be added to the addinslist *(as a matter of fact I use it myself)*. Since there is interest I will be happy to keep developing in and add some more operators.

**Comment by salim-b** [comment]
>  I will be happy for extraInserts to be added to the addinslist

ok, just made a [pull request](https://github.com/daattali/addinslist/pull/80). hope, that's fine :)
